#+TITLE: NEURON project
#+DATE: 2020-04-01
#+OPTIONS: toc:nil author:nil title:nil date:nil num:nil ^:{} \n:1 todo:nil
#+PROPERTY: header-args :eval never-export
#+LATEX_HEADER: \usepackage[margin=1.0in]{geometry}
#+LATEX_HEADER: \hypersetup{colorlinks=true,citecolor=black,linkcolor=black,urlcolor=blue,linkbordercolor=blue,pdfborderstyle={/S/U/W 1}}
#+LATEX_HEADER: \usepackage[round]{natbib}
#+LATEX_HEADER: \renewcommand{\bibsection}
#+ARCHIVE: daily_archive.org::datetree/* From master todo


* Implementation
  While originally based on [[https://journals.physiology.org/doi/full/10.1152/jn.1999.82.6.3006][Shen...Hines 1999]], I have adapted the basic parts of that model to Python using an object oriented style to simplify experimental control and data analysis. 

I used a number of channels and techniques described very well by [[https://www.frontiersin.org/articles/10.3389/fncel.2020.00040/full][Zbili et al. 2020]] (which were based on channels from [[https://www.nature.com/articles/nn.2359][Hu et al. 2009]])

For more on the basic implementation (including myelin sheaths, ion channel distributions, and nodes of Ranvier), see [[file:python/notebooks/presentation_slideshow.ipynb][this notebook]]. 

* AIS experiments
For examples of experiments, please see the final presentation [[file:python/notebooks/NEURON_class_presentation202007.ipynb][here]]. 

* Model testing and data anlysis
I have written some helper AP analysis functions, (so far) just a set of functions for AP amplitude and to measure FWHM for AP shape. Those functions are in [[file:python/mitral_cell/actionpotential.py][actionpotential.py]]. I have also written [[file:python/tests/][tests]] for many of these functions which can be run with [[https://docs.pytest.org/en/latest/contents.html][pytest]]. 
I am also working on tests for the main =MitralCell= class, to ensure that experimental changes are accurately reflected in the model as I think they are. I have not implemented those yet, but it will involve using =cell.ais.psection()= and verifying the output is as expected after changing. 
